name = "Bicategorical Whitehead"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["«Bicategorical Whitehead»"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"

[[lean_lib]]
name = "«Bicategorical Whitehead»"
